/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotcompatibleRouteImport } from './routes/notcompatible'
import { Route as StayaheadRouteImport } from './routes/stayahead'
import { Route as SupermarketshowdownRouteImport } from './routes/supermarketshowdown'
import { Route as UninvitedRouteImport } from './routes/uninvited'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotcompatibleRoute = NotcompatibleRouteImport.update({
  id: '/notcompatible',
  path: '/notcompatible',
  getParentRoute: () => rootRouteImport,
} as any)
const StayaheadRoute = StayaheadRouteImport.update({
  id: '/stayahead',
  path: '/stayahead',
  getParentRoute: () => rootRouteImport,
} as any)
const SupermarketshowdownRoute = SupermarketshowdownRouteImport.update({
  id: '/supermarketshowdown',
  path: '/supermarketshowdown',
  getParentRoute: () => rootRouteImport,
} as any)
const UninvitedRoute = UninvitedRouteImport.update({
  id: '/uninvited',
  path: '/uninvited',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notcompatible': typeof NotcompatibleRoute
  '/stayahead': typeof StayaheadRoute
  '/supermarketshowdown': typeof SupermarketshowdownRoute
  '/uninvited': typeof UninvitedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notcompatible': typeof NotcompatibleRoute
  '/stayahead': typeof StayaheadRoute
  '/supermarketshowdown': typeof SupermarketshowdownRoute
  '/uninvited': typeof UninvitedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notcompatible': typeof NotcompatibleRoute
  '/stayahead': typeof StayaheadRoute
  '/supermarketshowdown': typeof SupermarketshowdownRoute
  '/uninvited': typeof UninvitedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notcompatible'
    | '/stayahead'
    | '/supermarketshowdown'
    | '/uninvited'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notcompatible'
    | '/stayahead'
    | '/supermarketshowdown'
    | '/uninvited'
  id:
    | '__root__'
    | '/'
    | '/notcompatible'
    | '/stayahead'
    | '/supermarketshowdown'
    | '/uninvited'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotcompatibleRoute: typeof NotcompatibleRoute
  StayaheadRoute: typeof StayaheadRoute
  SupermarketshowdownRoute: typeof SupermarketshowdownRoute
  UninvitedRoute: typeof UninvitedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notcompatible': {
      id: '/notcompatible'
      path: '/notcompatible'
      fullPath: '/notcompatible'
      preLoaderRoute: typeof NotcompatibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stayahead': {
      id: '/stayahead'
      path: '/stayahead'
      fullPath: '/stayahead'
      preLoaderRoute: typeof StayaheadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supermarketshowdown': {
      id: '/supermarketshowdown'
      path: '/supermarketshowdown'
      fullPath: '/supermarketshowdown'
      preLoaderRoute: typeof SupermarketshowdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uninvited': {
      id: '/uninvited'
      path: '/uninvited'
      fullPath: '/uninvited'
      preLoaderRoute: typeof UninvitedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotcompatibleRoute: NotcompatibleRoute,
  StayaheadRoute: StayaheadRoute,
  SupermarketshowdownRoute: SupermarketshowdownRoute,
  UninvitedRoute: UninvitedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
